# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: ruby-plsql 0.7.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby-plsql".freeze
  s.version = "0.7.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Raimonds Simanovskis".freeze]
  s.date = "2018-09-03"
  s.description = "  ruby-plsql gem provides simple Ruby API for calling Oracle PL/SQL procedures.\n  It could be used both for accessing Oracle PL/SQL API procedures in legacy applications\n  as well as it could be used to create PL/SQL unit tests using Ruby testing libraries.\n".freeze
  s.email = "raimonds.simanovskis@gmail.com".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".codeclimate.yml",
    ".github/stale.yml",
    ".rubocop.yml",
    ".travis.yml",
    ".travis/oracle/download.sh",
    ".travis/oracle/install.sh",
    ".travis/setup_accounts.sh",
    "Gemfile",
    "History.txt",
    "License.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "Vagrantfile",
    "gemfiles/Gemfile.activerecord-5.0",
    "gemfiles/Gemfile.activerecord-5.1",
    "gemfiles/Gemfile.activerecord-5.2",
    "lib/plsql/connection.rb",
    "lib/plsql/helpers.rb",
    "lib/plsql/jdbc_connection.rb",
    "lib/plsql/oci8_patches.rb",
    "lib/plsql/oci_connection.rb",
    "lib/plsql/package.rb",
    "lib/plsql/procedure.rb",
    "lib/plsql/procedure_call.rb",
    "lib/plsql/schema.rb",
    "lib/plsql/sequence.rb",
    "lib/plsql/sql_statements.rb",
    "lib/plsql/table.rb",
    "lib/plsql/type.rb",
    "lib/plsql/variable.rb",
    "lib/plsql/version.rb",
    "lib/plsql/view.rb",
    "lib/ruby-plsql.rb",
    "lib/ruby_plsql.rb",
    "ruby-plsql.gemspec",
    "spec/plsql/connection_spec.rb",
    "spec/plsql/package_spec.rb",
    "spec/plsql/procedure_spec.rb",
    "spec/plsql/schema_spec.rb",
    "spec/plsql/sequence_spec.rb",
    "spec/plsql/sql_statements_spec.rb",
    "spec/plsql/table_spec.rb",
    "spec/plsql/type_spec.rb",
    "spec/plsql/variable_spec.rb",
    "spec/plsql/version_spec.rb",
    "spec/plsql/view_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/support/create_arunit_user.sql",
    "spec/support/custom_config.rb.sample",
    "spec/support/file_check_script.sh",
    "spec/support/test_db.rb",
    "spec/support/unlock_and_setup_hr_user.sql"
  ]
  s.homepage = "http://github.com/rsim/ruby-plsql".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.7".freeze
  s.summary = "Ruby API for calling Oracle PL/SQL procedures.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new("1.2.0") then
      s.add_development_dependency("juwelier".freeze, ["~> 2.0"])
      s.add_development_dependency("rspec_junit_formatter".freeze, [">= 0"])
      s.add_development_dependency("rake".freeze, [">= 10.0"])
      s.add_development_dependency("rspec".freeze, ["~> 3.1"])
      s.add_development_dependency("activerecord".freeze, ["~> 5.0"])
      s.add_development_dependency("activerecord-oracle_enhanced-adapter".freeze, ["~> 1.7"])
      s.add_development_dependency("simplecov".freeze, [">= 0"])
      s.add_development_dependency("ruby-oci8".freeze, ["~> 2.1"])
    else
      s.add_dependency("juwelier".freeze, ["~> 2.0"])
      s.add_dependency("rspec_junit_formatter".freeze, [">= 0"])
      s.add_dependency("rake".freeze, [">= 10.0"])
      s.add_dependency("rspec".freeze, ["~> 3.1"])
      s.add_dependency("activerecord".freeze, ["~> 5.0"])
      s.add_dependency("activerecord-oracle_enhanced-adapter".freeze, ["~> 1.7"])
      s.add_dependency("simplecov".freeze, [">= 0"])
      s.add_dependency("ruby-oci8".freeze, ["~> 2.1"])
    end
  else
    s.add_dependency("juwelier".freeze, ["~> 2.0"])
    s.add_dependency("rspec_junit_formatter".freeze, [">= 0"])
    s.add_dependency("rake".freeze, [">= 10.0"])
    s.add_dependency("rspec".freeze, ["~> 3.1"])
    s.add_dependency("activerecord".freeze, ["~> 5.0"])
    s.add_dependency("activerecord-oracle_enhanced-adapter".freeze, ["~> 1.7"])
    s.add_dependency("simplecov".freeze, [">= 0"])
    s.add_dependency("ruby-oci8".freeze, ["~> 2.1"])
  end
end
