# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-plsql}
  s.version = "0.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Raimonds Simanovskis"]
  s.date = %q{2010-10-06}
  s.description = %q{ruby-plsql gem provides simple Ruby API for calling Oracle PL/SQL procedures.
It could be used both for accessing Oracle PL/SQL API procedures in legacy applications
as well as it could be used to create PL/SQL unit tests using Ruby testing libraries.
}
  s.email = %q{raimonds.simanovskis@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "History.txt",
     "License.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/plsql/connection.rb",
     "lib/plsql/helpers.rb",
     "lib/plsql/jdbc_connection.rb",
     "lib/plsql/oci8_patches.rb",
     "lib/plsql/oci_connection.rb",
     "lib/plsql/package.rb",
     "lib/plsql/procedure.rb",
     "lib/plsql/procedure_call.rb",
     "lib/plsql/schema.rb",
     "lib/plsql/sequence.rb",
     "lib/plsql/sql_statements.rb",
     "lib/plsql/table.rb",
     "lib/plsql/type.rb",
     "lib/plsql/variable.rb",
     "lib/plsql/version.rb",
     "lib/plsql/view.rb",
     "lib/ruby-plsql.rb",
     "lib/ruby_plsql.rb",
     "ruby-plsql.gemspec",
     "spec/plsql/connection_spec.rb",
     "spec/plsql/package_spec.rb",
     "spec/plsql/procedure_spec.rb",
     "spec/plsql/schema_spec.rb",
     "spec/plsql/sequence_spec.rb",
     "spec/plsql/sql_statements_spec.rb",
     "spec/plsql/table_spec.rb",
     "spec/plsql/type_spec.rb",
     "spec/plsql/variable_spec.rb",
     "spec/plsql/version_spec.rb",
     "spec/plsql/view_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rsim/ruby-plsql}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby API for calling Oracle PL/SQL procedures.}
  s.test_files = [
    "spec/plsql/connection_spec.rb",
     "spec/plsql/package_spec.rb",
     "spec/plsql/procedure_spec.rb",
     "spec/plsql/schema_spec.rb",
     "spec/plsql/sequence_spec.rb",
     "spec/plsql/sql_statements_spec.rb",
     "spec/plsql/table_spec.rb",
     "spec/plsql/type_spec.rb",
     "spec/plsql/variable_spec.rb",
     "spec/plsql/version_spec.rb",
     "spec/plsql/view_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
      s.add_development_dependency(%q<activerecord>, ["= 2.3.8"])
      s.add_development_dependency(%q<activerecord-oracle_enhanced-adapter>, ["~> 1.3.1"])
    else
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
      s.add_dependency(%q<activerecord>, ["= 2.3.8"])
      s.add_dependency(%q<activerecord-oracle_enhanced-adapter>, ["~> 1.3.1"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    s.add_dependency(%q<activerecord>, ["= 2.3.8"])
    s.add_dependency(%q<activerecord-oracle_enhanced-adapter>, ["~> 1.3.1"])
  end
end

