name: test_11g

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        ruby: [
          '4.0',
          '3.4',
          '3.3',
          '3.2',
          ruby-head,
          ruby-debug,
          truffleruby,
          truffleruby-head
        ]
    env:
      ORACLE_HOME: /opt/oracle/instantclient_21_15
      LD_LIBRARY_PATH: /opt/oracle/instantclient_21_15
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
      TNS_ADMIN: ./ci/network/admin
      DATABASE_NAME: XE
      TZ: Europe/Riga
      DATABASE_SYS_PASSWORD: Oracle18

    services:
      oracle:
        image: gvenzl/oracle-xe:11
        ports:
          - 1521:1521
        env:
          TZ: Europe/Riga
          ORACLE_PASSWORD: Oracle18
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Create symbolic link for libaio library compatibility
      run: |
        sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
    - name: Download Oracle instant client
      run: |
        wget -q https://download.oracle.com/otn_software/linux/instantclient/2115000/instantclient-basic-linux.x64-21.15.0.0.0dbru.zip
        wget -q https://download.oracle.com/otn_software/linux/instantclient/2115000/instantclient-sqlplus-linux.x64-21.15.0.0.0dbru.zip
        wget -q https://download.oracle.com/otn_software/linux/instantclient/2115000/instantclient-sdk-linux.x64-21.15.0.0.0dbru.zip
    - name: Install Oracle instant client
      run: |
        sudo mkdir -p /opt/oracle/
        sudo unzip -q instantclient-basic-linux.x64-21.15.0.0.0dbru.zip -d /opt/oracle
        sudo unzip -qo instantclient-sqlplus-linux.x64-21.15.0.0.0dbru.zip -d /opt/oracle
        sudo unzip -qo instantclient-sdk-linux.x64-21.15.0.0.0dbru.zip -d /opt/oracle
        echo "/opt/oracle/instantclient_21_15" >> $GITHUB_PATH
    - name: Install JDBC Driver
      run: |
        wget -q https://download.oracle.com/otn-pub/otn_software/jdbc/233/ojdbc11.jar -O ./lib/ojdbc11.jar
    - name: Create database user
      run: |
        ./ci/setup_accounts.sh
    - name: Disable ActiveRecord for TruffleRuby
      run: |
        echo "NO_ACTIVERECORD=true" >> $GITHUB_ENV
      if: "contains(matrix.ruby, 'truffleruby')"
    - name: Bundle install
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        RUBYOPT=-w bundle exec rspec
