name: test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        ruby: [
          '3.2',
          '3.1',
          '3.0',
          '2.7',
          '2.6',
          '2.5',
          ruby-head,
          ruby-debug,
          truffleruby,
          truffleruby-head
        ]
    env:
      ORACLE_HOME: /usr/lib/oracle/21/client64
      LD_LIBRARY_PATH: /usr/lib/oracle/21/client64/lib
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
      TNS_ADMIN: ./ci/network/admin
      DATABASE_NAME: XEPDB1
      TZ: Europe/Riga
      DATABASE_SYS_PASSWORD: Oracle18
      DATABASE_VERSION: 21.3.0.0

    services:
      oracle:
        image: gvenzl/oracle-xe:latest
        ports:
          - 1521:1521
        env:
          TZ: Europe/Riga
          ORACLE_PASSWORD: Oracle18
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install required package
      run: |
        sudo apt-get install alien
    - name: Download Oracle client
      run: |
        wget -q https://download.oracle.com/otn_software/linux/instantclient/2110000/oracle-instantclient-basic-21.10.0.0.0-1.x86_64.rpm
        wget -q https://download.oracle.com/otn_software/linux/instantclient/2110000/oracle-instantclient-sqlplus-21.10.0.0.0-1.x86_64.rpm
        wget -q https://download.oracle.com/otn_software/linux/instantclient/2110000/oracle-instantclient-devel-21.10.0.0.0-1.x86_64.rpm
    - name: Install Oracle client
      run: |
        sudo alien -i oracle-instantclient-basic-21.10.0.0.0-1.x86_64.rpm
        sudo alien -i oracle-instantclient-sqlplus-21.10.0.0.0-1.x86_64.rpm
        sudo alien -i oracle-instantclient-devel-21.10.0.0.0-1.x86_64.rpm
    - name: Install JDBC Driver
      run: |
        wget -q https://download.oracle.com/otn-pub/otn_software/jdbc/211/ojdbc11.jar -O ./lib/ojdbc11.jar
    - name: Create database user
      run: |
        ./ci/setup_accounts.sh
    - name: Disable ActiveRecord for TruffleRuby
      run: |
        echo "NO_ACTIVERECORD=true" >> $GITHUB_ENV
      if: "contains(matrix.ruby, 'truffleruby')"
    - name: Bundle install
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
